version: "3.7"

services:
  BackEnd:
    # Image name
    image: splurge-easy-back-end
    # Container name
    container_name: SEBackEnd
    # Build the image from the Dockerfile
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    # Mount the current directory as a volume to the container
    volumes:
      - ./back-end:/src
      - frontend_build:/build
    # command
    command: bash start.sh
    # Map port 3000 on the host to port 3000 on the container
    ports:
      - "8000:8000"

  FrontEnd:
    # Image name
    image: splurge-easy-front-end
    # Container name
    container_name: SEFrontEnd
    # Build the image from the Dockerfile
    build: 
      context: ./front-end/
      dockerfile: Dockerfile
    # Mount the current directory as a volume to the container
    volumes:
      - ./front-end:/src
      - frontend_build:/build
    # command
    command: bash start.sh
    # Map port 3000 on the host to port 3000 on the container
    ports:
      - "3000:3000"

volumes:
  frontend_build: