# Generated by Django 4.2.7 on 2023-12-11 04:27

from django.db import migrations, models
import django.db.models.deletion
import uuid

from expense.models import SplitMethod

def create_split_methods(apps, schema_editor):
    split_methods = ['E', 'P', 'U', 'S']
    split_method_objs = []
    for split_method in split_methods:
        split_method_objs.append(SplitMethod(id=split_method))

    SplitMethod.objects.bulk_create(split_method_objs)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitMethod',
            fields=[
                ('id', models.CharField(choices=[('E', 'Equal'), ('P', 'Percentage'), ('U', 'Unqually'), ('S', 'Shares')], max_length=1, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_on', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_details', to='expense.expense')),
            ],
        ),
        migrations.RunPython(
            create_split_methods
        ),
    ]
